(let ()
  (define (A k x1 x2 x3 x4 x5)
    (define (B)
      (set! k (- k 1))
      (A k B x1 x2 x3 x4))
    (if (<= k 0)
        (+ (x4) (x5))
        (B)))
  (let ((z-1 (lambda () -1))
        (z (lambda () 0))
        (z+1 (lambda () 1)))
    (write (A 18 z+1 z-1 z-1 z+1 z))
    (newline)))