(let ()
  (define (write-line x) (write x) (newline))
  (write-line (apply (lambda (x y) (+ x y)) (list 2 3)))
  (write-line (apply + (list 2 3)))
  (write-line (apply (lambda (f vs) (apply f vs)) (list + (list 2 3))))
  (write-line (apply apply (list apply (list + (list 2 3)))))
)
