(let ()
  (define (writeln e)
    (write e) (newline))
  (define (iota n)
    (let recur ((i 0))
      (if (>= i n) '() (cons i (recur (+ i 1))))))
  (define sqr (lambda (x) (* x x)))
  (define x 3)
  (define y 4)
  (define f (lambda (x y) (+ (sqr x) (sqr y))))
  (writeln (iota (f x y)))
  )