(let ((s (make-string 4 #\一))
      (t "道法自然"))
  (write s) (newline)
  (write t) (newline)
  (write (string? t)) (write (string? s)) (newline)
  (write (string-length t)) (newline)
  (write (string-length s)) (newline)
  (write (string-ref s 0)) (newline)
  (string-set! s 0 #\浑)
  (string-set! s 1 #\然)
  (string-set! s 3 #\体)
  (write s)
  (newline)
  (write (string-ref s 0)) (newline)
  (write (string-ref s 1)) (newline)
  (write (string-ref s 2)) (newline)
  (write (string-ref s 3)) (newline)
  (write (char? (string-ref s 0)))
  (write (char? (string-ref s 1)))
  (write (char? (string-ref s 2)))
  (write (char? (string-ref s 3)))
  (newline)
  )