(write (char->integer #\newline)) (newline)
(write (integer->char 10)) (newline)
(write (char->integer #\nul)) (newline)
(write (integer->char 0)) (newline)
(write (integer->char (char->integer #\A))) (newline)
(write (integer->char (char->integer #\a))) (newline)
(write (char->integer (integer->char 65))) (newline)
(write (char->integer (integer->char 97))) (newline)
(write (integer? (char->integer #\nul))) (newline)
(write (char? (integer->char 0))) (newline)
(write (boolean? (integer? (char->integer #\nul)))) (newline)
(write (boolean? (char? (integer->char 0)))) (newline)
