(pretty-print 25)
(pretty-print 0)
(pretty-print -2357)
(pretty-print #t)
(pretty-print #f)
(pretty-print #\t)
(pretty-print #\f)
(pretty-print (char->integer #\A))
(pretty-print (integer->char 65))
(pretty-print (integer->char (char->integer #\A)))
(pretty-print (char->integer (integer->char 65)))
(pretty-print (integer->char 0))
(pretty-print (integer->char 32))
(pretty-print (integer->char 10))
(pretty-print (add1 10))
(pretty-print (sub1 14))
(pretty-print (- -17))
; (pretty-print #\nul)
(pretty-print #\space)
(pretty-print #\newline)

(pretty-print (char? #\t))
(pretty-print (char? (integer->char 32)))
(pretty-print (char? 42))
(pretty-print (char? #t))
(pretty-print (char? #f))

(pretty-print (boolean? #t))
(pretty-print (boolean? #f))
(pretty-print (boolean? 42))
(pretty-print (boolean? #\t))
(pretty-print (boolean? #\f))
(pretty-print (boolean? #\D))
(pretty-print (boolean? (integer->char 32)))

(pretty-print (integer? 42))
(pretty-print (integer? (char->integer #\E)))
(pretty-print (integer? -1))
(pretty-print (integer? #t))
(pretty-print (integer? #f))
(pretty-print (integer? #\t))
(pretty-print (integer? #\f))
(pretty-print (integer? #\D))

; (newline)
; (pretty-print (zero? 0))
; (pretty-print (zero? 42))
; (pretty-print (zero? #t))
; (pretty-print (zero? #f))
; (pretty-print (zero? -1))

; (newline)
; (pretty-print (zero? (char->integer #\nul)))
; (pretty-print (zero? #\t))
; (pretty-print (zero? #\f))
; (pretty-print (zero? #\D))