(write
(and (not (car (cons #f #t)))
     (not (cdr (cons #t #f)))
     (not (caar (cons (cons #f #t) #t)))
     (not (caaar (cons (cons (cons #f #t) #t) #t)))
     (not (caaaar (cons (cons (cons (cons #f #t) #t) #t) #t)))
     (not (cdaaar (cons (cons (cons (cons #t #f) #t) #t) #t)))
     (not (cdaar (cons (cons (cons #t #f) #t) #t)))
     (not (cadaar (cons (cons (cons #t (cons #f #t)) #t) #t)))
     (not (cddaar (cons (cons (cons #t (cons #t #f)) #t) #t)))
     (not (cdar (cons (cons #t #f) #t)))
     (not (cadar (cons (cons #t (cons #f #t)) #t)))
     (not (caadar (cons (cons #t (cons (cons #f #t) #t)) #t)))
     (not (cdadar (cons (cons #t (cons (cons #t #f) #t)) #t)))
     (not (cddar (cons (cons #t (cons #t #f)) #t)))
     (not (caddar (cons (cons #t (cons #t (cons #f #t))) #t)))
     (not (cdddar (cons (cons #t (cons #t (cons #t #f))) #t)))
     (not (cadr (cons #t (cons #f #t))))
     (not (caadr (cons #t (cons (cons #f #t) #t))))
     (not (caaadr (cons #t (cons (cons (cons #f #t) #t) #t))))
     (not (cdaadr (cons #t (cons (cons (cons #t #f) #t) #t))))
     (not (cdadr (cons #t (cons (cons #t #f) #t))))
     (not (cadadr (cons #t (cons (cons #t (cons #f #t)) #t))))
     (not (cddadr (cons #t (cons (cons #t (cons #t #f)) #t))))
     (not (cddr (cons #t (cons #t #f))))
     (not (caddr (cons #t (cons #t (cons #f #t)))))
     (not (caaddr (cons #t (cons #t (cons (cons #f #t) #t)))))
     (not (cdaddr (cons #t (cons #t (cons (cons #t #f) #t)))))
     (not (cdddr (cons #t (cons #t (cons #t #f)))))
     (not (cadddr (cons #t (cons #t (cons #t (cons #f #t))))))
     (not (cddddr (cons #t (cons #t (cons #t (cons #t #f)))))))
)
(newline)
