(write (cons 1 #f))
(newline)
(write (pair? (cons 1 #f)))
(newline)
(write (car (cons 1 #f)))
(newline)
(write (cdr (cons 1 #f)))
(newline)
(write (cons 1 (cons 2 (cons 3 #f))))
(newline)
(write (cons 1 (cons 2 (cons 3 '()))))
(newline)
(let ((p (cons 1 2)))
  (write p) (newline)
  (set-cdr! p #t)
  (write p) (newline)
  (set-car! p #\t)
  (write p) (newline))