(let ()
  (define (writeln x) (write x) (newline))
  (define (list . x) x)
  (writeln (apply (lambda (x y) (+ x y)) (list 2 3)))
  (writeln (apply + (list 2 3)))
  (writeln (apply (lambda (f vs) (apply f vs)) (list + (list 2 3))))
  (writeln (apply apply (list apply (list + (list 2 3)))))
)
