(write (char? #t))
(write (boolean? #t))
(write (integer? #t))
(write (null? #t))
(write (eof-object? #t))
(newline)
(write (boolean? (char? #t)))
(write (boolean? (boolean? #t)))
(write (boolean? (integer? #t)))
(write (boolean? (null? #t)))
(write (boolean? (eof-object? #t)))
(newline)

(write (char? #f))
(write (boolean? #f))
(write (integer? #f))
(write (null? #f))
(write (eof-object? #f))
(newline)
(write (boolean? (char? #f)))
(write (boolean? (boolean? #f)))
(write (boolean? (integer? #f)))
(write (boolean? (null? #f)))
(write (boolean? (eof-object? #f)))
(newline)

(write (char? #\a))
(write (boolean? #\a))
(write (integer? #\a))
(write (null? #\a))
(write (eof-object? #\a))
(newline)
(write (boolean? (char? #\a)))
(write (boolean? (boolean? #\a)))
(write (boolean? (integer? #\a)))
(write (boolean? (null? #\a)))
(write (boolean? (eof-object? #\a)))
(newline)

(write (char? '()))
(write (boolean? '()))
(write (integer? '()))
(write (null? '()))
(write (eof-object? '()))
(newline)
(write (boolean? (char? '())))
(write (boolean? (boolean? '())))
(write (boolean? (integer? '())))
(write (boolean? (null? '())))
(write (boolean? (eof-object? '())))
(newline)

(write (char? (eof-object)))
(write (boolean? (eof-object)))
(write (integer? (eof-object)))
(write (null? (eof-object)))
(write (eof-object? (eof-object)))
(newline)
(write (boolean? (char? (eof-object))))
(write (boolean? (boolean? (eof-object))))
(write (boolean? (integer? (eof-object))))
(write (boolean? (null? (eof-object))))
(write (boolean? (eof-object? (eof-object))))
(newline)
