(let* ((str "列表")
       (hash 0)
       (s (%make-symbol hash str)))
  (%symbol-value-set! s (lambda x x))
  (write (symbol? s))
  (newline)
  (write ((%symbol-value s) (%symbol-name s) (procedure? (%symbol-value s)) (%symbol-hash s)))
  (newline)
)