(let ()
  (define (writeln x) (write x) (newline))
  (let ((ip (open-input-file "test/始计篇.txt")))
    (writeln (read-char ip))
    (writeln (peek-char ip))
    (writeln (peek-char ip))
    (writeln (eq? (peek-char ip) (peek-char ip)))
    (let* ((c (peek-char ip))
           (d (read-char ip)))
      (writeln (eq? c d)))
    (let ((c (read-char ip)))
      (writeln c)
      (unread-char c ip)
      (writeln (eq? c (read-char ip))))
    (close-port ip)))