(let ()
  (define (utf32->utf8! c32 buf)
    (let ((c32 (char->integer c32)))
      (cond
        ((<= c32 #x7F)
         (bytevector-u8-set! buf 0 c32)
         1)
        ((<= c32 #x7FF)
         (bytevector-u8-set! buf 0 (bitwise-ior #xC0 (ash c32 -6)))
         (bytevector-u8-set! buf 1 (bitwise-ior #x80 (bitwise-and c32 #x3F)))
         2)
        ((and (<= c32 #xFFFF)
              (>= c32 #xD800)
              (<= c32 #xDFFF))
         0)
        ((<= c32 #xFFFF)
         (bytevector-u8-set! buf 0 (bitwise-ior #xE0 (ash c32 -12)))
         (bytevector-u8-set! buf 1 (bitwise-ior #x80 (bitwise-and (ash c32 -6) #x3F)))
         (bytevector-u8-set! buf 2 (bitwise-ior #x80 (bitwise-and c32 #x3F)))
         3)
        ((<= c32 #x10FFFF)
         (bytevector-u8-set! buf 0 (bitwise-ior #xF0 (ash c32 -18)))
         (bytevector-u8-set! buf 1 (bitwise-ior #x80 (bitwise-and (ash c32 -12) #x3F)))
         (bytevector-u8-set! buf 2 (bitwise-ior #x80 (bitwise-and (ash c32 -6) #x3F)))
         (bytevector-u8-set! buf 3 (bitwise-ior #x80 (bitwise-and c32 #x3F)))
         4)
        (else 0))))
  (define write-char
    (let ((buf (make-bytevector 4)))
      (lambda (ch)
        (foreign-call s_fwrite buf 0 (utf32->utf8! ch buf) (label stdout)))))
  (define (puts s)
    (let loop ((i 0))
      (if (< i (string-length s))
          (begin
            (write-char (string-ref s i))
            (loop (+ i 1))))))
  (puts "兵者，国之大事，死生之地，存亡之道，不可不察也。")
  (write-char #\newline)
  (puts "语者，算之枢机，人机之桥，逻辑之形，不可不精也。")
  (write-char #\newline)
)
