(let ()
(define (fold-left f init xs)
  (if (pair? xs)
      (fold-left f (f init (car xs)) (cdr xs))
      init))
(define (iota i)
  (let recur ((j 0))
    (if (>= j i) '() (cons j (recur (add1 j))))))
(write (fold-left + 0 (iota 100)))
(newline)
)