(pretty-print (+ 3 5))
(pretty-print (* 3 5))
(pretty-print (- 3 5))
(pretty-print (+ (* 3 3) (* 4 4)))
(pretty-print (= 0 0))
(pretty-print (= 0 1))
(pretty-print (< 0 0))
(pretty-print (< 0 -1))
(pretty-print (< -1 0))
(pretty-print (<= 0 0))
(pretty-print (<= 0 -1))
(pretty-print (<= -1 0))
(pretty-print (> 0 0))
(pretty-print (> 0 -1))
(pretty-print (> -1 0))
(pretty-print (>= 0 0))
(pretty-print (>= 0 -1))
(pretty-print (>= -1 0))