(let ((inp (open-input-file "test/test-reader.scm")))
  (define (read-sexps inp)
    (let ((obj (read inp)))
      (if (eof-object? obj)
          '()
          (cons obj (read-sexps inp)))))
  (write (read-sexps inp))
  (newline)
  (close-port inp)
)