(write #t) (newline)
(write #f) (newline)
(write '()) (newline)
(write (eof-object)) (write (newline)) (newline)
(write (void)) (newline)
(write #\t) (newline)
(write #\f) (newline)
(write #\你) (newline)
(write #\好) (newline)
