(pretty-print 'something)
(pretty-print (symbol? 'something))
(pretty-print (symbol? "something"))
(pretty-print (symbol? (string->symbol "something")))
(pretty-print (symbol? (symbol->string (string->symbol "something"))))
(pretty-print (symbol? (string->symbol (symbol->string 'something))))
(pretty-print (list 'something 'something))
(pretty-print (eq? 'something 'something))
(pretty-print (symbol->string 'something))
(pretty-print (string->symbol "something"))
(pretty-print (eq? (string->symbol "something") 'something))