(write (fixnum-width)) (newline)
(write (fxabs -1)) (newline)
(write (fxabs 0)) (newline)
(write (fxabs 11)) (newline)
(write (fxabs -13)) (newline)
(write (fxlength 1)) (newline)
(write (fxlength 11)) (newline)
(write (fxlength 13)) (newline)
(write (fxlength 29)) (newline)
(write (fxlength 0)) (newline)
(write (fxlength -1)) (newline) ;;; TODO: what should be the value?
(write (fxlength -11)) (newline)
(write (fxlength -13)) (newline)
(write (fxlength -29)) (newline)
(write (fxmax 20 -10)) (newline)
(write (fxmax 20 23)) (newline)
(write (fxmax 20 20)) (newline)
(write (fxmax 0 0)) (newline)