(let ((list (lambda x x))
      (writeln (lambda (x) (write x) (newline))))
(writeln (apply (lambda (x y) (+ x y)) (list 2 3)))
(writeln (apply (lambda (x y) (+ x y)) 2 (list 3)))
(let ((f (lambda (x y . z)
          (if (< x y)
              z
              (cons x (cons y z))))))
  (writeln (apply f 1 (list 2)))
  (writeln (apply f -7 7 (list "reimu" "yes")))
  (writeln (apply f 2 1 (list #t))))
(let ((f (lambda (x y . z)
          (if (< x y)
              z
              (cons x (cons y z))))))
(define (list? x)
  (or (null? x)
      (and (pair? x)
           (list? (cdr x)))))

(define (%apply f args . args*)
  (if (null? args*)
      (apply f args)
      (apply f
             (let list* ((x args) (xs args*))
              (if (pair? xs)
                  (cons x (list* (car xs) (cdr xs)))
                  (if (list? x) x '()))))))
(writeln (apply %apply (list f 1 (list 2))))
(writeln (apply %apply (list f -7 7 (list "reimu" "yes"))))
(writeln (apply %apply (list f 2 1 (list #t))))
)
(writeln (apply list 1 2 3 '(1 2 3)))
)