(define primitive-meta-table `(
  ,@(if (getenv "FOREIGN_IO")
        '([write #f #f (write e1)])
        '())
  ,@(if (getenv "FOREIGN_IO")
        '([newline #f #f (newline)])
        '())
  [procedure? #t ,procedure? (procedure? e1)]
  [void #t ,void (void)]
  [eof-object? #t ,eof-object? (eof-object? e1)]
  [eof-object #t ,eof-object (eof-object)]
  [eq? #t ,eq? (eq? e1 e2)]
  [boolean? #t ,boolean? (boolean? e1)]
  [not #t ,not (not e1)]
  [null? #t ,null? (null? e1)]
  [integer? #t ,integer? (integer? e1)]
  [add1 #t ,add1 (add1 e1)]
  [sub1 #t ,sub1 (sub1 e1)]
  [* #t ,* (* e1 e2)]
  [+ #t ,+ (+ e1 e2)]
  [- #t ,- (case-lambda ((e1) (- 0 e1)) ((e1 e2) (- e1 e2)))]
  [div #t ,div (div e1 e2)]
  [mod #t ,mod (mod e1 e2)]
  [< #t ,< (< e1 e2)]
  [<= #t ,<= (<= e1 e2)]
  [= #t ,= (= e1 e2)]
  [>= #t ,>= (>= e1 e2)]
  [> #t ,> (> e1 e2)]
  [abs #t ,abs (abs e1)]
  [max #t ,max (max e1 e2)]
  [ash #t ,ash (ash e1 e2)]
  [bitwise-ior #t ,bitwise-ior (bitwise-ior e1 e2)]
  [bitwise-and #t ,bitwise-and (bitwise-and e1 e2)]
  [char? #t ,char? (char? e1)]
  [integer->char #t ,integer->char (integer->char e1)]
  [char->integer #t ,char->integer (char->integer e1)]
  [string? #t ,string? (string? e1)]
  [string #t #f #f]
  [make-string #t #f (make-string e1 e2)]
  [string-length #t ,string-length (string-length e1)]
  [string-ref #t ,string-ref (string-ref e1 e2)]
  [string-set! #f #f (string-set! e1 e2 e3)]
  [vector? #t ,vector? (vector? e1)]
  [vector #t #f (lambda x (list->vector x))]
  [make-vector #t #f (make-vector e1 e2)]
  [vector-length #t ,vector-length (vector-length e1)]
  [vector-ref #t ,vector-ref (vector-ref e1 e2)]
  [vector-set! #f #f (vector-set! e1 e2 e3)]
  [bytevector? #t ,bytevector? (bytevector? e1)]
  [bytevector-length #t ,bytevector-length (bytevector-length e1)]
  [make-bytevector #t #f (make-bytevector e1 e2)]
  [bytevector-u8-ref #t ,bytevector-u8-ref (bytevector-u8-ref e1 e2)]
  [bytevector-u8-set! #f #f (bytevector-u8-set! e1 e2 e3)]
  [pair? #t ,pair? (pair? e1)]
  [cons #t #f (cons e1 e2)]
  [car #t ,car (car e1)]
  [cdr #t ,cdr (cdr e1)]
  [set-car! #f #f (set-car! e1 e2)]
  [set-cdr! #f #f (set-cdr! e1 e2)]
  [list #t #f #f]
  [equal? #t ,equal? #f]
  [memq #t ,memq #f]
  [apply #t #f (apply e1 e2)]
  [call-with-values #f #f (call-with-values e1 e2)]
  [values* #f #f #f]
  [values #f #f (lambda xs (apply values* xs))]
  ,@(if (getenv "PRIM_CALLCC")
        '([call/cc #f #f #f])
        '())
  [$call/cc #f #f #f]
  [symbol? #t ,symbol? (symbol? e1)]
  [%make-symbol #t #f #f]
  [%symbol-name #t #f #f]
  [%symbol-value #t #f #f]
  [%symbol-value-set! #f #f #f]
  [%symbol-hash #t #f #f]
  [symbol-hash #t ,symbol-hash (symbol-hash e)]
  [collect #f #f #f]
  [caar #t ,caar (caar x)]
  [caaar #t ,caaar (caaar x)]
  [caaaar #t ,caaaar (caaaar x)]
  [cdaaar #t ,cdaaar (cdaaar x)]
  [cdaar #t ,cdaar (cdaar x)]
  [cadaar #t ,cadaar (cadaar x)]
  [cddaar #t ,cddaar (cddaar x)]
  [cdar #t ,cdar (cdar x)]
  [cadar #t ,cadar (cadar x)]
  [caadar #t ,caadar (caadar x)]
  [cdadar #t ,cdadar (cdadar x)]
  [cddar #t ,cddar (cddar x)]
  [caddar #t ,caddar (caddar x)]
  [cdddar #t ,cdddar (cdddar x)]
  [cadr #t ,cadr (cadr x)]
  [caadr #t ,caadr (caadr x)]
  [caaadr #t ,caaadr (caaadr x)]
  [cdaadr #t ,cdaadr (cdaadr x)]
  [cdadr #t ,cdadr (cdadr x)]
  [cadadr #t ,cadadr (cadadr x)]
  [cddadr #t ,cddadr (cddadr x)]
  [cddr #t ,cddr (cddr x)]
  [caddr #t ,caddr (caddr x)]
  [caaddr #t ,caaddr (caaddr x)]
  [cdaddr #t ,cdaddr (cdaddr x)]
  [cdddr #t ,cdddr (cdddr x)]
  [cadddr #t ,cadddr (cadddr x)]
  [cddddr #t ,cddddr (cddddr x)]
))
