(let ()
(define (list . xs) xs)

(define (vector . xs)
  (let recur ((i 0) (xs xs))
    (if (pair? xs)
        (let ((v (recur (add1 i) (cdr xs))))
          (vector-set! v i (car xs))
          v)
        (make-vector i 0))))

(define (bytevector . xs)
  (let recur ((i 0) (xs xs))
    (if (pair? xs)
        (let ((v (recur (add1 i) (cdr xs))))
          (bytevector-u8-set! v i (car xs))
          v)
        (make-bytevector i 0))))

(define (writeln x)
  (write x)
  (newline))

(writeln
  (let loop ((obj '()) (t 'something) (i 0))
    (if (> i 10000)
        (cons "done" obj)
        (let ((b (bytevector 1 2 3 4 5 6 7 8))
              (x (vector 1 2 3 4))
              (y (list 1 2 3 4 5 6 7 8 9 10))
              (z "something"))
        (if (and (eq? (string->symbol (symbol->string t)) (string->symbol (symbol->string t)))
                 (eq? (string->symbol (symbol->string t)) t)
                 (eq? (vector-length x) 4)
                 (eq? (bytevector-length b) 8)
                 (eq? t 'something))
            (loop (list x y z) t (add1 i))
            (list t 'something
                  (symbol->string t) (symbol->string 'something)
                  (eq? (string->symbol (symbol->string t)) (string->symbol (symbol->string t)))
                  (eq? (string->symbol (symbol->string t)) t)
                  (eq? t 'something)
                  ))))))
)